exclude: [
  'node_modules/**',
  'src/style/vendor/**'
]

linters:
  ZeroUnit:
    enabled: false
  LeadingZero:
    enabled: false
  PropertySortOrder:
    enabled: false
  NestingDepth:
    enabled: false
  SelectorDepth:
    enabled: false
  UnnecessaryParentReference:
    enabled: false
  IdSelector:
    enabled: false
  SelectorFormat:
    enabled: false
